version: '3'

services:

####################################
#### SETUP ANDROID CONTAINER ####
####################################
    # android:
    #     image: android:alpine
    #     ports:
    #         - "8080"
    #     networks:
    #         - back-tier
    #     restart: always

####################################
#### SETUP JAVA SERVER CONTAINER ####
####################################
    server:
        build: 
            context: ./server
        environment: 
            JAVA_DEV: developement
        networks:
            - back-tier
        depends_on:
            - db
            - android
        restart: always

####################################
#### SETUP    DB      CONTAINER ####
####################################
    db:
        image: postgres:alpine
        ports:
            - "5999:5999"
        # env_file:
        #     - database.env
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
        volumes:
            - db-data:/var/lib/postgresql/data
            - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
        networks:
            - back-tier
        restart: always

volumes:
    db-data:
        
networks:
    # server -> db + android
    back-tier:
# adminer:
#         image: adminer
#         restart: always
#         ports:
#           - 8080:8080
#docker-compose up