version: '2'

services:
  mysql:
    image: mysql
    container_name: "cashmanager"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: postgres

  cashmanager:
    build: .
    container_name: cashmanager
    ports:
      - "9090:8080"
      - '9797:8787'
    depends_on:
      - mysql